### ISSUE TITLE
Add simple GUI

### ISSUE THREAD

**Issue by Symbian9** [haxpor/tt#1]
Is it possible add some simple GUI?

Maybe, you could use `mlib` toolkit (X11-based)

- https://github.com/Symbian9/azpainter/tree/master/mlib

### REFERNCE

- https://github.com/Symbian9/azpainter
- http://azsky2.html.xdomain.jp/linux/mthemeeditor.html

**Comment by haxpor** [comment]
Hi, thanks for suggestion. No plan for GUI, only command line for this project.
